### ISSUE TITLE
Problem in SpyTorchTutorial2

### ISSUE THREAD

**Issue by ghost** [fzenke/spytorch#1]
Hello,

It was a very nice and interesting tutorial, thank you for preparing it...

tutorial1 haven't any problem, but in tutorial 2, some dtype problems occurred... after their fixation, training process was very slow on GTX 980 (I've run on this config some very deep model)... could you please explain your config, and also training time and response time?

**Comment by fzenke** [comment]
Hi. I am not sure I fully understand your question. Slow training is not entirely unexpected for a very deep architecture since you are simulating a recurrent neural network over many time steps. The configuration I used was merely a simple example with a small number of leaky integrate-and-fire hidden units. What exactly do you mean by response time?

**Comment by fzenke** [comment]
I just pushed some changes to Tutorial 2. I hope this fixes the dtype problems.

**Comment by iman-aliabdi** [comment]
Hi 
Thank you for publishing a beautiful notebook, there were some problems in SpyTorchTutorial2 in sparse_data_generator() function on GPU which I could fix them as follows.

        # i = torch.LongTensor(coo,device=device) 
        # Fixed as:
        i = torch.tensor(coo, dtype=torch.int64, device=device) 
        
        #v = torch.FloatTensor(np.ones(len(coo[0])),device=device)
        # Fixed as:
        v = torch.tensor(np.ones(len(coo[0])), dtype=torch.float, device=device)  

        # X_batch = torch.sparse.FloatTensor(i, v, torch.Size([batch_size,nb_steps,nb_units]))
        # Fixed as:
        if device == 'cuda':
            X_batch = torch.sparse.FloatTensor(i, v, torch.Size([batch_size,nb_steps,nb_units])).cuda()
        else:
            X_batch = torch.sparse.FloatTensor(i, v, torch.Size([batch_size,nb_steps,nb_units]))

After these modifications the problems fixed and the code will run on GPU with the reasonable speedup.

**Comment by fzenke** [comment]
Thanks for suggesting this. I just pushed an updated version incorporating some of your suggestions. Could you check if that works on your machine?

**Comment by iman-aliabdi** [comment]
Thanks a lot, I just check the new version you have pushed. The problem has fixed, but there are just some extra SPACE before "def sparse_data_generator()".
![Capture1](https://user-images.githubusercontent.com/38804087/56127474-7e47a800-5f92-11e9-905d-5edc0f73ee39.JPG)

After removing these spaces which prevent defining the function, the code will run without any problem on colab.research.google with a TESLA K80 GPU.

Best
Iman

**Comment by fzenke** [comment]
Thanks, I removed the space and will close this issue now.
