### ISSUE TITLE
Spike times shifted

### ISSUE THREAD

**Issue by smonsays** [fzenke/spytorch#10]
I have the impression that the spike recordings are shifted one time step in all tutorials. Could you maybe check if this is indeed the case?

From my understanding, time step 0 is recorded twice for the spikes, once during initialisation
```python
  mem = torch.zeros((batch_size, nb_hidden), device=device, dtype=dtype)
  spk_rec = [mem]
```
and once within the simulation of time step 0:
```python
  for t in range(nb_steps):
      mthr = mem-1.0
      out = spike_fn(mthr)
      ...
      spk_rec.append(out)
```
As a result the indeces appear shifted when comparing
```python
print(torch.nonzero((mem_rec-1.0) > 0.0))
print(torch.nonzero(spk_rec))
```
Thanks,
Simon

**Comment by fzenke** [comment]
You are right. It's better to initialize the recordings as empty lists.

**Comment by smonsays** [comment]
Thanks for the quick response!

Just to clarify since I think I am missing something: With both recordings initialized as empty lists, the offset I was referring to persists, i.e. `spk_rec[i]` now corresponds to  `mem_rec[i-1]`. If we assume that spiking is instantaneous and happens within the same time step as the membrane potential crosses the threshold, this is what appeared to be inconsistent to me.

**Comment by fzenke** [comment]
Does the issue still persist with the new commit? We changed the order in which the new state is updated and add to the list.

**Comment by smonsays** [comment]
Ah yes, that solved it, I think!
