### ISSUE TITLE
propagation delay

### ISSUE THREAD

**Issue by yizx6** [fzenke/spytorch#11]
Hi zenke, 
I have a question about the snn model. If I feed a spike image to a snn with L layers at time step n, the output of the last layer will be affected by the input at time step n + L - 1. In deep networks, the delay should be considered, because it will increase the whole  time steps.
<img width="436" alt="Screen Shot 2021-12-15 at 4 50 45 PM" src="https://user-images.githubusercontent.com/18640552/146157747-b8cb70dc-d8be-476a-b8b4-4b07b72a372f.png">

**Comment by fzenke** [comment]
That's correct. There is a transmission delay that should be taken into account. Moreover, the synaptic and neuronal dynamics will further add to this delay. In practice, however, most SNN implementations have hundreds of time-steps but usually not as many layers. I hope that clarifies it and happy new year.
