### ISSUE TITLE
Dataset never decompressed

### ISSUE THREAD

**Issue by AaronSpieler** [fzenke/spytorch#12]
Hello,

I belive I ran into a possible issue here.
Due to line 37 the evaluation in line 38 will always be false if one hasnt already got the uncompressed dataset.

https://github.com/fzenke/spytorch/blob/9e91eceaf53f17be9e95a3743164224bdbb086bb/notebooks/utils.py#L35-L42

If I change line 37 to:
`hdf5_file_path = gz_file_path[:-3]`
This works for me.

Best,
Aaron

**Comment by fzenke** [comment]
Thanks for reporting this. When inspecting the code, I also noted that the download cache seems broken.
