### ISSUE TITLE
Software/Machine description available?

### ISSUE THREAD

**Issue by muffgaga** [fzenke/spytorch#6]
Hey Friedemann,

thanks for making the examples available, they look very helpful.
However, to make them fully reproducible I think that some additional information regarding the "technical dependencies" is needed.

In particular, the list of used software packages (incl. version and build variant information) plus some specification about the machine hardware (CPU arch, GPUs).

Preferably, the former could be expressed as a recipe for constructing a container (Dockerfile, or for better HPC-compatibility, a
[Singularity](https://github.com/hpcng/singularity) [recipe](https://sylabs.io/guides/3.7/user-guide/definition_files.html)), maybe even using an explicitly versioning package manager like [spack](https://spack.readthedocs.io/en/latest/).

Cheers,
Eric

**Comment by hockman1** [comment]
Hmm this looks interesting. I was wondering if this can be done on other datasets such as iris datasets, wine datasets and so on? Just some of my thoughts

**Comment by fzenke** [comment]
I now added a requirement.txt. I agree, singularity would be rad. Feel free to submit a pull request.

**Comment by fzenke** [comment]
> Hmm this looks interesting. I was wondering if this can be done on other datasets such as iris datasets, wine datasets and so on? Just some of my thoughts

Yes, that's entirely possible.
